@startuml
'https://plantuml.com/activity-diagram-beta

left to right direction

package "ftl" {

class MainCommand [[../../../test_runner/src/main/kotlin/ftl/Main.kt]] {
    flank.jar
}

package "cli" {

class AuthCommand [[../../../test_runner/src/main/kotlin/ftl/cli/AuthCommand.kt]] {
    auth
}
class FirebaseCommand [[../../../test_runner/src/main/kotlin/ftl/cli/FirebaseCommand.kt]] {
    firebase
}

package "auth" {
class LoginCommand [[../../../test_runner/src/main/kotlin/ftl/cli/auth/LoginCommand.kt]] #lightblue {
    login
}
}


package "firebase" {

class CancelCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/CancelCommand.kt]] #lightblue {
    cancel
}
class RefreshCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/RefreshCommand.kt]] #lightblue {
    refresh
}
class TestCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/TestCommand.kt]] {
    test
}

package "test" {

class AndroidCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/AndroidCommand.kt]] {
    android
}
class IosCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/IosCommand.kt]] {
    ios
}
class IPBlocksCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/IPBlocksCommand.kt]] {
    ip-blocks
}
class NetworkProfilesCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/NetworkProfilesCommand.kt]] {
    network-profiles
}
class ProvidedSoftwareCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/ProvidedSoftwareCommand.kt]] {
    provided-software
}

package "android" {

class AndroidDoctorCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidDoctorCommand.kt]] #lightblue {
    doctor
}
class AndroidLocalesCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidLocalesCommand.kt]] {
    locales
}
class AndroidModelsCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidModelsCommand.kt]] {
    models
}
class AndroidOrientationsCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidOrientationsCommand.kt]] {
    screen-orientations
}
class AndroidRunCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt]] #lightblue {
    run
}
class AndroidTestEnvironmentCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidTestEnvironmentCommand.kt]] #lightblue {
    test-environment
}
class AndroidVersionsCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidVersionsCommand.kt]] {
    versions
}

package "android.locales" {
class AndroidLocalesListCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/android/configuration/AndroidLocalesListCommand.kt]] #lightblue {
    list
}
class AndroidLocalesDescribeCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/android/configuration/AndroidLocalesDescribeCommand.kt]] #lightblue {
    describe
}
}

package "android.models" {
class AndroidModelsListCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/android/models/AndroidModelsListCommand.kt]] #lightblue {
    list
}
class AndroidModelDescribeCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/android/models/AndroidModelDescribeCommand.kt]] #lightblue {
    describe
}
}

package "android.orientations" {
class AndroidOrientationsListCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/android/orientations/AndroidOrientationsListCommand.kt]] #lightblue {
    list
}
}

package "android.versions" {
class AndroidVersionsListCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/android/versions/AndroidVersionsListCommand.kt]] #lightblue {
    list
}
class AndroidVersionsDescribeCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/android/versions/AndroidVersionsDescribeCommand.kt]] #lightblue {
    describe
}
}
}


package "ios" {

class IosDoctorCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosDoctorCommand.kt]] #lightblue {
    doctor
}

class IosLocalesCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosLocalesCommand.kt]] {
    locales
}
class IosModelsCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosModelsCommand.kt]] {
    models
}
class IosOrientationsCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosOrientationsCommand.kt]] {
    screen-orientations
}
class IosRunCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt]] #lightblue {
    run
}
class IosTestEnvironmentCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosTestEnvironmentCommand.kt]] #lightblue {
    test-environment
}
class IosVersionsCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosVersionsCommand.kt]] {
    versions
}

package "ios.locales" {
class IosLocalesListCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/configuration/IosLocalesListCommand.kt]] #lightblue {
    list
}
class IosLocalesDescribeCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/configuration/IosLocalesDescribeCommand.kt]] #lightblue {
    describe
}
}

package "ios.models" {
class IosModelsListCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/models/IosModelsListCommand.kt]] #lightblue {
    list
}
class IosModelDescribeCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/models/IosModelDescribeCommand.kt]] #lightblue {
    describe
}
}

package "ios.orientations" {
class IosOrientationsListCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/orientations/IosOrientationsListCommand.kt]] #lightblue {
    list
}
}

package "ios.versions" {
class IosVersionsListCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/versions/IosVersionsListCommand.kt]] #lightblue {
    list
}
class IosVersionsDescribeCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/versions/IosVersionsDescribeCommand.kt]] #lightblue {
    describe
}
}

}

package "ipblocks" {
class IPBlocksListCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/ipblocks/IPBlocksListCommand.kt]] #lightblue {
    list
}
}

package "networkprofiles" {
class NetworkProfilesDescribeCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/networkprofiles/NetworkProfilesDescribeCommand.kt]] #lightblue {
    describe
}
class NetworkProfilesListCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/networkprofiles/NetworkProfilesListCommand.kt]] #lightblue {
    list
}
}

package "providedsoftware" {
class ProvidedSoftwareListCommand [[../../../test_runner/src/main/kotlin/ftl/cli/firebase/test/providedsoftware/ProvidedSoftwareListCommand.kt]] #lightblue {
    list
}
}
}
}
}
}

MainCommand --> RefreshCommand
MainCommand --> CancelCommand
MainCommand --> ProvidedSoftwareCommand
MainCommand --> NetworkProfilesCommand
MainCommand --> IPBlocksCommand
MainCommand --> AuthCommand
MainCommand --> IosCommand
MainCommand --> AndroidCommand
MainCommand --> FirebaseCommand

AuthCommand --> LoginCommand

IPBlocksCommand --> IPBlocksListCommand

IosCommand --> IosRunCommand
IosCommand --> IosDoctorCommand
IosCommand --> IosModelsCommand
IosCommand --> IosVersionsCommand
IosCommand --> IosLocalesCommand
IosCommand --> IosOrientationsCommand
IosCommand --> IosTestEnvironmentCommand

IosModelsCommand --> IosModelsListCommand
IosModelsCommand --> IosModelDescribeCommand

IosVersionsCommand --> IosVersionsListCommand
IosVersionsCommand --> IosVersionsDescribeCommand

IosLocalesCommand --> IosLocalesListCommand
IosLocalesCommand --> IosLocalesDescribeCommand

IosOrientationsCommand --> IosOrientationsListCommand

AndroidCommand --> AndroidRunCommand
AndroidCommand --> AndroidDoctorCommand
AndroidCommand --> AndroidModelsCommand
AndroidCommand --> AndroidVersionsCommand
AndroidCommand --> AndroidLocalesCommand
AndroidCommand --> AndroidOrientationsCommand
AndroidCommand --> AndroidTestEnvironmentCommand

AndroidModelsCommand --> AndroidModelsListCommand
AndroidModelsCommand --> AndroidModelDescribeCommand

AndroidVersionsCommand --> AndroidVersionsListCommand
AndroidVersionsCommand --> AndroidVersionsDescribeCommand

AndroidLocalesCommand --> AndroidLocalesListCommand
AndroidLocalesCommand --> AndroidLocalesDescribeCommand

AndroidOrientationsCommand --> AndroidOrientationsListCommand

FirebaseCommand --> TestCommand
FirebaseCommand --> RefreshCommand
FirebaseCommand --> CancelCommand

TestCommand --> AndroidCommand
TestCommand --> IosCommand
TestCommand --> NetworkProfilesCommand
TestCommand --> ProvidedSoftwareCommand
TestCommand --> IPBlocksCommand

NetworkProfilesCommand --> NetworkProfilesDescribeCommand
NetworkProfilesCommand --> NetworkProfilesListCommand

ProvidedSoftwareCommand --> ProvidedSoftwareListCommand
@enduml
