/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.testing.model;

/**
 * An Android package file to install.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Testing API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Apk extends com.google.api.client.json.GenericJson {

  /**
   * The path to an APK to be installed on the device before the test begins.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private FileReference location;

  /**
   * The java package for the APK to be installed. Value is determined by examining the
   * application's manifest.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String packageName;

  /**
   * The path to an APK to be installed on the device before the test begins.
   * @return value or {@code null} for none
   */
  public FileReference getLocation() {
    return location;
  }

  /**
   * The path to an APK to be installed on the device before the test begins.
   * @param location location or {@code null} for none
   */
  public Apk setLocation(FileReference location) {
    this.location = location;
    return this;
  }

  /**
   * The java package for the APK to be installed. Value is determined by examining the
   * application's manifest.
   * @return value or {@code null} for none
   */
  public java.lang.String getPackageName() {
    return packageName;
  }

  /**
   * The java package for the APK to be installed. Value is determined by examining the
   * application's manifest.
   * @param packageName packageName or {@code null} for none
   */
  public Apk setPackageName(java.lang.String packageName) {
    this.packageName = packageName;
    return this;
  }

  @Override
  public Apk set(String fieldName, Object value) {
    return (Apk) super.set(fieldName, value);
  }

  @Override
  public Apk clone() {
    return (Apk) super.clone();
  }

}
