/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.testing.model;

/**
 * Android application details based on application manifest and apk archive contents.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Testing API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ApkDetail extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ApkManifest apkManifest;

  /**
   * @return value or {@code null} for none
   */
  public ApkManifest getApkManifest() {
    return apkManifest;
  }

  /**
   * @param apkManifest apkManifest or {@code null} for none
   */
  public ApkDetail setApkManifest(ApkManifest apkManifest) {
    this.apkManifest = apkManifest;
    return this;
  }

  @Override
  public ApkDetail set(String fieldName, Object value) {
    return (ApkDetail) super.set(fieldName, value);
  }

  @Override
  public ApkDetail clone() {
    return (ApkDetail) super.clone();
  }

}
