/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.testing.model;

/**
 * An Android App Bundle file format, containing a BundleConfig.pb file, a base module directory,
 * zero or more dynamic feature module directories. See https://developer.android.com/guide/app-
 * bundle/build for guidance on building App Bundles.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Testing API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AppBundle extends com.google.api.client.json.GenericJson {

  /**
   * .aab file representing the app bundle under test.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private FileReference bundleLocation;

  /**
   * .aab file representing the app bundle under test.
   * @return value or {@code null} for none
   */
  public FileReference getBundleLocation() {
    return bundleLocation;
  }

  /**
   * .aab file representing the app bundle under test.
   * @param bundleLocation bundleLocation or {@code null} for none
   */
  public AppBundle setBundleLocation(FileReference bundleLocation) {
    this.bundleLocation = bundleLocation;
    return this;
  }

  @Override
  public AppBundle set(String fieldName, Object value) {
    return (AppBundle) super.set(fieldName, value);
  }

  @Override
  public AppBundle clone() {
    return (AppBundle) super.clone();
  }

}
