/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.testing.model;

/**
 * A single device IP block
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Testing API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class DeviceIpBlock extends com.google.api.client.json.GenericJson {

  /**
   * The date this block was added to Firebase Test Lab
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Date addedDate;

  /**
   * An IP address block in CIDR notation eg: 34.68.194.64/29
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String block;

  /**
   * Whether this block is used by physical or virtual devices
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String form;

  /**
   * The date this block was added to Firebase Test Lab
   * @return value or {@code null} for none
   */
  public Date getAddedDate() {
    return addedDate;
  }

  /**
   * The date this block was added to Firebase Test Lab
   * @param addedDate addedDate or {@code null} for none
   */
  public DeviceIpBlock setAddedDate(Date addedDate) {
    this.addedDate = addedDate;
    return this;
  }

  /**
   * An IP address block in CIDR notation eg: 34.68.194.64/29
   * @return value or {@code null} for none
   */
  public java.lang.String getBlock() {
    return block;
  }

  /**
   * An IP address block in CIDR notation eg: 34.68.194.64/29
   * @param block block or {@code null} for none
   */
  public DeviceIpBlock setBlock(java.lang.String block) {
    this.block = block;
    return this;
  }

  /**
   * Whether this block is used by physical or virtual devices
   * @return value or {@code null} for none
   */
  public java.lang.String getForm() {
    return form;
  }

  /**
   * Whether this block is used by physical or virtual devices
   * @param form form or {@code null} for none
   */
  public DeviceIpBlock setForm(java.lang.String form) {
    this.form = form;
    return this;
  }

  @Override
  public DeviceIpBlock set(String fieldName, Object value) {
    return (DeviceIpBlock) super.set(fieldName, value);
  }

  @Override
  public DeviceIpBlock clone() {
    return (DeviceIpBlock) super.clone();
  }

}
