/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.testing.model;

/**
 * List of IP blocks used by the Firebase Test Lab
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Testing API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class DeviceIpBlockCatalog extends com.google.api.client.json.GenericJson {

  /**
   * The device IP blocks used by Firebase Test Lab
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<DeviceIpBlock> ipBlocks;

  static {
    // hack to force ProGuard to consider DeviceIpBlock used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(DeviceIpBlock.class);
  }

  /**
   * The device IP blocks used by Firebase Test Lab
   * @return value or {@code null} for none
   */
  public java.util.List<DeviceIpBlock> getIpBlocks() {
    return ipBlocks;
  }

  /**
   * The device IP blocks used by Firebase Test Lab
   * @param ipBlocks ipBlocks or {@code null} for none
   */
  public DeviceIpBlockCatalog setIpBlocks(java.util.List<DeviceIpBlock> ipBlocks) {
    this.ipBlocks = ipBlocks;
    return this;
  }

  @Override
  public DeviceIpBlockCatalog set(String fieldName, Object value) {
    return (DeviceIpBlockCatalog) super.set(fieldName, value);
  }

  @Override
  public DeviceIpBlockCatalog clone() {
    return (DeviceIpBlockCatalog) super.clone();
  }

}
