/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.testing.model;

/**
 * The section of an tag. https://developer.android.com/guide/topics/manifest/intent-filter-
 * element.html
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Testing API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class IntentFilter extends com.google.api.client.json.GenericJson {

  /**
   * The android:name value of the tag.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> actionNames;

  /**
   * The android:name value of the tag.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> categoryNames;

  /**
   * The android:mimeType value of the tag.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String mimeType;

  /**
   * The android:name value of the tag.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getActionNames() {
    return actionNames;
  }

  /**
   * The android:name value of the tag.
   * @param actionNames actionNames or {@code null} for none
   */
  public IntentFilter setActionNames(java.util.List<java.lang.String> actionNames) {
    this.actionNames = actionNames;
    return this;
  }

  /**
   * The android:name value of the tag.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getCategoryNames() {
    return categoryNames;
  }

  /**
   * The android:name value of the tag.
   * @param categoryNames categoryNames or {@code null} for none
   */
  public IntentFilter setCategoryNames(java.util.List<java.lang.String> categoryNames) {
    this.categoryNames = categoryNames;
    return this;
  }

  /**
   * The android:mimeType value of the tag.
   * @return value or {@code null} for none
   */
  public java.lang.String getMimeType() {
    return mimeType;
  }

  /**
   * The android:mimeType value of the tag.
   * @param mimeType mimeType or {@code null} for none
   */
  public IntentFilter setMimeType(java.lang.String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

  @Override
  public IntentFilter set(String fieldName, Object value) {
    return (IntentFilter) super.set(fieldName, value);
  }

  @Override
  public IntentFilter clone() {
    return (IntentFilter) super.clone();
  }

}
