/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.testing.model;

/**
 * A single iOS device.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Testing API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class IosDevice extends com.google.api.client.json.GenericJson {

  /**
   * Required. The id of the iOS device to be used. Use the TestEnvironmentDiscoveryService to get
   * supported options.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String iosModelId;

  /**
   * Required. The id of the iOS major software version to be used. Use the
   * TestEnvironmentDiscoveryService to get supported options.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String iosVersionId;

  /**
   * Required. The locale the test device used for testing. Use the TestEnvironmentDiscoveryService
   * to get supported options.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String locale;

  /**
   * Required. How the device is oriented during the test. Use the TestEnvironmentDiscoveryService
   * to get supported options.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String orientation;

  /**
   * Required. The id of the iOS device to be used. Use the TestEnvironmentDiscoveryService to get
   * supported options.
   * @return value or {@code null} for none
   */
  public java.lang.String getIosModelId() {
    return iosModelId;
  }

  /**
   * Required. The id of the iOS device to be used. Use the TestEnvironmentDiscoveryService to get
   * supported options.
   * @param iosModelId iosModelId or {@code null} for none
   */
  public IosDevice setIosModelId(java.lang.String iosModelId) {
    this.iosModelId = iosModelId;
    return this;
  }

  /**
   * Required. The id of the iOS major software version to be used. Use the
   * TestEnvironmentDiscoveryService to get supported options.
   * @return value or {@code null} for none
   */
  public java.lang.String getIosVersionId() {
    return iosVersionId;
  }

  /**
   * Required. The id of the iOS major software version to be used. Use the
   * TestEnvironmentDiscoveryService to get supported options.
   * @param iosVersionId iosVersionId or {@code null} for none
   */
  public IosDevice setIosVersionId(java.lang.String iosVersionId) {
    this.iosVersionId = iosVersionId;
    return this;
  }

  /**
   * Required. The locale the test device used for testing. Use the TestEnvironmentDiscoveryService
   * to get supported options.
   * @return value or {@code null} for none
   */
  public java.lang.String getLocale() {
    return locale;
  }

  /**
   * Required. The locale the test device used for testing. Use the TestEnvironmentDiscoveryService
   * to get supported options.
   * @param locale locale or {@code null} for none
   */
  public IosDevice setLocale(java.lang.String locale) {
    this.locale = locale;
    return this;
  }

  /**
   * Required. How the device is oriented during the test. Use the TestEnvironmentDiscoveryService
   * to get supported options.
   * @return value or {@code null} for none
   */
  public java.lang.String getOrientation() {
    return orientation;
  }

  /**
   * Required. How the device is oriented during the test. Use the TestEnvironmentDiscoveryService
   * to get supported options.
   * @param orientation orientation or {@code null} for none
   */
  public IosDevice setOrientation(java.lang.String orientation) {
    this.orientation = orientation;
    return this;
  }

  @Override
  public IosDevice set(String fieldName, Object value) {
    return (IosDevice) super.set(fieldName, value);
  }

  @Override
  public IosDevice clone() {
    return (IosDevice) super.clone();
  }

}
