/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.testing.model;

/**
 * A version-specific information of an iOS model.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Testing API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PerIosVersionInfo extends com.google.api.client.json.GenericJson {

  /**
   * A static capacity of an iOS version.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String deviceCapacity;

  /**
   * An iOS version.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String versionId;

  /**
   * A static capacity of an iOS version.
   * @return value or {@code null} for none
   */
  public java.lang.String getDeviceCapacity() {
    return deviceCapacity;
  }

  /**
   * A static capacity of an iOS version.
   * @param deviceCapacity deviceCapacity or {@code null} for none
   */
  public PerIosVersionInfo setDeviceCapacity(java.lang.String deviceCapacity) {
    this.deviceCapacity = deviceCapacity;
    return this;
  }

  /**
   * An iOS version.
   * @return value or {@code null} for none
   */
  public java.lang.String getVersionId() {
    return versionId;
  }

  /**
   * An iOS version.
   * @param versionId versionId or {@code null} for none
   */
  public PerIosVersionInfo setVersionId(java.lang.String versionId) {
    this.versionId = versionId;
    return this;
  }

  @Override
  public PerIosVersionInfo set(String fieldName, Object value) {
    return (PerIosVersionInfo) super.set(fieldName, value);
  }

  @Override
  public PerIosVersionInfo clone() {
    return (PerIosVersionInfo) super.clone();
  }

}
