/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.testing.model;

/**
 * Options for enabling sharding.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Testing API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ShardingOption extends com.google.api.client.json.GenericJson {

  /**
   * Shards test cases into the specified groups of packages, classes, and/or methods.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ManualSharding manualSharding;

  /**
   * Uniformly shards test cases given a total number of shards.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private UniformSharding uniformSharding;

  /**
   * Shards test cases into the specified groups of packages, classes, and/or methods.
   * @return value or {@code null} for none
   */
  public ManualSharding getManualSharding() {
    return manualSharding;
  }

  /**
   * Shards test cases into the specified groups of packages, classes, and/or methods.
   * @param manualSharding manualSharding or {@code null} for none
   */
  public ShardingOption setManualSharding(ManualSharding manualSharding) {
    this.manualSharding = manualSharding;
    return this;
  }

  /**
   * Uniformly shards test cases given a total number of shards.
   * @return value or {@code null} for none
   */
  public UniformSharding getUniformSharding() {
    return uniformSharding;
  }

  /**
   * Uniformly shards test cases given a total number of shards.
   * @param uniformSharding uniformSharding or {@code null} for none
   */
  public ShardingOption setUniformSharding(UniformSharding uniformSharding) {
    this.uniformSharding = uniformSharding;
    return this;
  }

  @Override
  public ShardingOption set(String fieldName, Object value) {
    return (ShardingOption) super.set(fieldName, value);
  }

  @Override
  public ShardingOption clone() {
    return (ShardingOption) super.clone();
  }

}
