/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.testing.model;

/**
 * A starting intent specified by an action, uri, and categories.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Testing API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class StartActivityIntent extends com.google.api.client.json.GenericJson {

  /**
   * Action name. Required for START_ACTIVITY.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String action;

  /**
   * Intent categories to set on the intent.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> categories;

  /**
   * URI for the action.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String uri;

  /**
   * Action name. Required for START_ACTIVITY.
   * @return value or {@code null} for none
   */
  public java.lang.String getAction() {
    return action;
  }

  /**
   * Action name. Required for START_ACTIVITY.
   * @param action action or {@code null} for none
   */
  public StartActivityIntent setAction(java.lang.String action) {
    this.action = action;
    return this;
  }

  /**
   * Intent categories to set on the intent.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getCategories() {
    return categories;
  }

  /**
   * Intent categories to set on the intent.
   * @param categories categories or {@code null} for none
   */
  public StartActivityIntent setCategories(java.util.List<java.lang.String> categories) {
    this.categories = categories;
    return this;
  }

  /**
   * URI for the action.
   * @return value or {@code null} for none
   */
  public java.lang.String getUri() {
    return uri;
  }

  /**
   * URI for the action.
   * @param uri uri or {@code null} for none
   */
  public StartActivityIntent setUri(java.lang.String uri) {
    this.uri = uri;
    return this;
  }

  @Override
  public StartActivityIntent set(String fieldName, Object value) {
    return (StartActivityIntent) super.set(fieldName, value);
  }

  @Override
  public StartActivityIntent clone() {
    return (StartActivityIntent) super.clone();
  }

}
