/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.testing.model;

/**
 * Model definition for SystraceSetup.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Testing API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SystraceSetup extends com.google.api.client.json.GenericJson {

  /**
   * Systrace duration in seconds. Should be between 1 and 30 seconds. 0 disables systrace.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer durationSeconds;

  /**
   * Systrace duration in seconds. Should be between 1 and 30 seconds. 0 disables systrace.
   * @return value or {@code null} for none
   */
  public java.lang.Integer getDurationSeconds() {
    return durationSeconds;
  }

  /**
   * Systrace duration in seconds. Should be between 1 and 30 seconds. 0 disables systrace.
   * @param durationSeconds durationSeconds or {@code null} for none
   */
  public SystraceSetup setDurationSeconds(java.lang.Integer durationSeconds) {
    this.durationSeconds = durationSeconds;
    return this;
  }

  @Override
  public SystraceSetup set(String fieldName, Object value) {
    return (SystraceSetup) super.set(fieldName, value);
  }

  @Override
  public SystraceSetup clone() {
    return (SystraceSetup) super.clone();
  }

}
