/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.testing.model;

/**
 * Uniformly shards test cases given a total number of shards. For Instrumentation test, it will be
 * translated to "-e numShard" "-e shardIndex" AndroidJUnitRunner arguments. With uniform sharding
 * enabled, specifying these sharding arguments via environment_variables is invalid.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Testing API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UniformSharding extends com.google.api.client.json.GenericJson {

  /**
   * Required. Total number of shards. When any physical devices are selected, the number must be >=
   * 1 and <= 50. When no physical devices are selected, the number must be >= 1 and <= 500.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer numShards;

  /**
   * Required. Total number of shards. When any physical devices are selected, the number must be >=
   * 1 and <= 50. When no physical devices are selected, the number must be >= 1 and <= 500.
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNumShards() {
    return numShards;
  }

  /**
   * Required. Total number of shards. When any physical devices are selected, the number must be >=
   * 1 and <= 50. When no physical devices are selected, the number must be >= 1 and <= 500.
   * @param numShards numShards or {@code null} for none
   */
  public UniformSharding setNumShards(java.lang.Integer numShards) {
    this.numShards = numShards;
    return this;
  }

  @Override
  public UniformSharding set(String fieldName, Object value) {
    return (UniformSharding) super.set(fieldName, value);
  }

  @Override
  public UniformSharding clone() {
    return (UniformSharding) super.clone();
  }

}
