/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.testing.model;

/**
 * An Xcode version that an iOS version is compatible with.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Testing API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class XcodeVersion extends com.google.api.client.json.GenericJson {

  /**
   * Tags for this Xcode version. Example: "default".
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> tags;

  /**
   * The id for this version. Example: "9.2".
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String version;

  /**
   * Tags for this Xcode version. Example: "default".
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getTags() {
    return tags;
  }

  /**
   * Tags for this Xcode version. Example: "default".
   * @param tags tags or {@code null} for none
   */
  public XcodeVersion setTags(java.util.List<java.lang.String> tags) {
    this.tags = tags;
    return this;
  }

  /**
   * The id for this version. Example: "9.2".
   * @return value or {@code null} for none
   */
  public java.lang.String getVersion() {
    return version;
  }

  /**
   * The id for this version. Example: "9.2".
   * @param version version or {@code null} for none
   */
  public XcodeVersion setVersion(java.lang.String version) {
    this.version = version;
    return this;
  }

  @Override
  public XcodeVersion set(String fieldName, Object value) {
    return (XcodeVersion) super.set(fieldName, value);
  }

  @Override
  public XcodeVersion clone() {
    return (XcodeVersion) super.clone();
  }

}
