#!/bin/sh

echo "Running ktlint check"
OUTPUT="/tmp/ktlint-$(date +%s)"
./gradlew formatKotlin > $OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat $OUTPUT
  rm $OUTPUT
  echo
  echo "***********************************************"
  echo "           Ktlint failed to autofix            "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
fi

if [ `git diff --cached --exit-code HEAD^ > /dev/null && (git ls-files --other --exclude-standard --directory | grep -c -v '/$')` ];
then
  $(git commit -a -m "Automatic commit for styling fixes")
fi

rm $OUTPUT
