#!/bin/sh

echo "Running ktlint check"
OUTPUT="/tmp/ktlint-$(date +%s)"
./gradlew lintKotlin > "$OUTPUT"
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat "$OUTPUT"
  rm "$OUTPUT"
  echo
  echo "***********************************************"
  echo "           Ktlint failed to autofix            "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
fi

rm "$OUTPUT"
