java_import(
    name = "google-api-services-storage-v1-rev1-1.18.0-rc",
    jars = ["google-api-services-storage-v1-rev1-1.18.0-rc.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "google-api-services-testing-v1-revsnapshot-1.20.0",
    jars = ["google-api-services-testing-v1-revsnapshot-1.20.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "google-api-services-toolresults-v1beta3-rev20151013-1.20.0",
    jars = ["google-api-services-toolresults-v1beta3-rev20151013-1.20.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
