/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.testing.model;

/**
 * Model definition for NetworkConfiguration.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google Cloud Testing API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class NetworkConfiguration extends com.google.api.client.json.GenericJson {

  /**
   * The emulation rule applying to the download traffic
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private TrafficRule downRule;

  /**
   * The unique opaque id for this network traffic configuration @OutputOnly
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The emulation rule applying to the upload traffic
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private TrafficRule upRule;

  /**
   * The emulation rule applying to the download traffic
   * @return value or {@code null} for none
   */
  public TrafficRule getDownRule() {
    return downRule;
  }

  /**
   * The emulation rule applying to the download traffic
   * @param downRule downRule or {@code null} for none
   */
  public NetworkConfiguration setDownRule(TrafficRule downRule) {
    this.downRule = downRule;
    return this;
  }

  /**
   * The unique opaque id for this network traffic configuration @OutputOnly
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * The unique opaque id for this network traffic configuration @OutputOnly
   * @param id id or {@code null} for none
   */
  public NetworkConfiguration setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * The emulation rule applying to the upload traffic
   * @return value or {@code null} for none
   */
  public TrafficRule getUpRule() {
    return upRule;
  }

  /**
   * The emulation rule applying to the upload traffic
   * @param upRule upRule or {@code null} for none
   */
  public NetworkConfiguration setUpRule(TrafficRule upRule) {
    this.upRule = upRule;
    return this;
  }

  @Override
  public NetworkConfiguration set(String fieldName, Object value) {
    return (NetworkConfiguration) super.set(fieldName, value);
  }

  @Override
  public NetworkConfiguration clone() {
    return (NetworkConfiguration) super.clone();
  }

}
