# Autoformatter friendly markdownlint config (all formatting rules disabled)
default: true
blank_lines: false
bullet: false
html: false
indentation: false
line_length: false
spaces: false
url: false
whitespace: false

# "Heading levels should only increment by one level at a time" fires on "Refereces" headings
MD001: false

# "Multiple headings with the same content" fires on "Example kotlin code"
MD024: false
