@startuml
'https://plantuml.com/activity-diagram-beta

start
skinparam ConditionEndStyle hline
:get shards;
partition "create iOS test contexts" #LightBlue {
  split
  partition "xc test run" #LightBlue {
    #snow :create counter;
    #snow :upload files;
    #snow :xc test run data as byte array;
    #snow :upload xc test file;
    #snow :xc test context>
  }
  split again
  partition "game loop test run" #LightBlue {
    #snow :create counter;
    #snow :upload files;
    #snow :game loop test context>
  }
  end split
}
end

@enduml
