/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.testing.model;

/**
 * Enables automatic Google account login. If set, the service will automatically generate a Google
 * test account and add it to the device, before executing the test. Note that test accounts might
 * be reused. Many applications show their full set of functionalities when an account is present on
 * the device. Logging into the device with these generated accounts allows testing more
 * functionalities.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google Cloud Testing API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleAuto extends com.google.api.client.json.GenericJson {

  @Override
  public GoogleAuto set(String fieldName, Object value) {
    return (GoogleAuto) super.set(fieldName, value);
  }

  @Override
  public GoogleAuto clone() {
    return (GoogleAuto) super.clone();
  }

}
