/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.testing.model;

/**
 * A storage location within Google cloud storage (GCS).
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google Cloud Testing API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleCloudStorage extends com.google.api.client.json.GenericJson {

  /**
   * The path to a directory in GCS that will eventually contain the results for this test. The
   * requesting user must have write access on the bucket in the supplied path. Required
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String gcsPath;

  /**
   * The path to a directory in GCS that will eventually contain the results for this test. The
   * requesting user must have write access on the bucket in the supplied path. Required
   * @return value or {@code null} for none
   */
  public java.lang.String getGcsPath() {
    return gcsPath;
  }

  /**
   * The path to a directory in GCS that will eventually contain the results for this test. The
   * requesting user must have write access on the bucket in the supplied path. Required
   * @param gcsPath gcsPath or {@code null} for none
   */
  public GoogleCloudStorage setGcsPath(java.lang.String gcsPath) {
    this.gcsPath = gcsPath;
    return this;
  }

  @Override
  public GoogleCloudStorage set(String fieldName, Object value) {
    return (GoogleCloudStorage) super.set(fieldName, value);
  }

  @Override
  public GoogleCloudStorage clone() {
    return (GoogleCloudStorage) super.clone();
  }

}
