// tag::picocli-generated-full-manpage[]

// tag::picocli-generated-man-section-name[]
== Name

flank.jar
-ios-run - Run tests on Firebase Test Lab

// end::picocli-generated-man-section-name[]

// tag::picocli-generated-man-section-synopsis[]
== Synopsis

*flank.jar
 ios run* [*-h*] [*--async*] [*--disable-results-upload*]
                   [*--disable-sharding*] [*--dry*] [*--dump-shards*]
                   [*--full-junit-result*] [*--ignore-failed-tests*]
                   [*--keep-file-path*] [*--no-record-video*] [*--obfuscate*]
                   [*--record-video*] [*--smart-flank-disable-upload*]
                   [*--use-average-test-time-for-new-tests*] [*-c*=_<configPath>_]
                   [*--default-test-time*=_<defaultTestTime>_]
                   [*--local-result-dir*=_<localResultsDir>_]
                   [*--max-test-shards*=_<maxTestShards>_]
                   [*--network-profile*=_<networkProfile>_]
                   [*--num-flaky-test-attempts*=_<flakyTestAttempts>_]
                   [*--num-test-runs*=_<repeatTests>_]
                   [*--output-style*=_<outputStyle>_] [*--project*=_<project>_]
                   [*--results-bucket*=_<resultsBucket>_]
                   [*--results-dir*=_<resultsDir>_]
                   [*--results-history-name*=_<resultsHistoryName>_]
                   [*--run-timeout*=_<runTimeout>_] [*--shard-time*=_<shardTime>_]
                   [*--smart-flank-gcs-path*=_<smartFlankGcsPath>_] [*--test*=_<test>_]
                   [*--timeout*=_<timeout>_] [*--xcode-version*=_<xcodeVersion>_]
                   [*--xctestrun-file*=_<xctestrunFile>_]
                   [*--client-details*=_<String=String>_[,_<String=String>_...]]...
                   [*--device*=_<String=String>_[,_<String=String>_...]]...
                   [*--files-to-download*=_<filesToDownload>_[,
                   _<filesToDownload>_...]]... [*--test-targets*=_<testTargets>_[,
                   _<testTargets>_...]]...
                   [*--test-targets-always-run*=_<testTargetsAlwaysRun>_[,
                   _<testTargetsAlwaysRun>_...]]...

// end::picocli-generated-man-section-synopsis[]

// tag::picocli-generated-man-section-description[]
== Description

Uploads the app and tests to GCS.
Runs the XCTests and XCUITests.
Configuration is read from flank.yml


// end::picocli-generated-man-section-description[]

// tag::picocli-generated-man-section-options[]
== Options

*-h*, *--help*::
  Prints this help message

*--dry*::
  Dry run on mock server

*-c*, *--config*=_<configPath>_::
  YAML config file path

*--obfuscate*::
  Replacing internal test names with unique identifiers when using --dump-shards option to avoid exposing internal details

*--device*=_<String=String>_[,_<String=String>_...]::
  A list of DIMENSION=VALUE pairs which specify a target device to test against. This flag may be repeated to specify multiple devices. The four device dimensions are: model, version, locale, and orientation. If any dimensions are omitted, they will use a default value. Omitting all of the preceding dimension-related flags will run tests against a single device using defaults for all four device dimensions.

*--results-bucket*=_<resultsBucket>_::
  The name of a Google Cloud Storage bucket where raw test results will be stored (default: "test-lab-<random-UUID>"). Note that the bucket must be owned by a billing-enabled project, and that using a non-default bucket will result in billing charges for the storage used.

*--results-dir*=_<resultsDir>_::
  The name of a unique Google Cloud Storage object within the results bucket where raw test results will be stored (default: a timestamp with a random suffix). Caution: if specified, this argument must be unique for each test matrix you create, otherwise results from multiple test matrices will be overwritten or intermingled.

*--record-video*::
  Enable video recording during the test. Disabled by default.

*--no-record-video*::
  Disable video recording during the test (default behavior). Use --record-video to enable.

*--timeout*=_<timeout>_::
  The max time this test execution can run before it is cancelled (default: 15m). It does not include any time necessary to prepare and clean up the target device. The maximum possible testing time is 30m on physical devices and 60m on virtual devices. The TIMEOUT units can be h, m, or s. If no unit is given, seconds are assumed. 

*--async*::
  Invoke a test asynchronously without waiting for test results.

*--client-details*=_<String=String>_[,_<String=String>_...]::
  Comma-separated, KEY=VALUE map of additional details to attach to the test matrix.Arbitrary KEY=VALUE pairs may be attached to a test matrix to provide additional context about the tests being run.When consuming the test results, such as in Cloud Functions or a CI system,these details can add additional context such as a link to the corresponding pull request.

*--network-profile*=_<networkProfile>_::
  The name of the network traffic profile, for example --network-profile=LTE, which consists of a set of parameters to emulate network conditions when running the test (default: no network shaping; see available profiles listed by the `flank test network-profiles list` command). This feature only works on physical devices. 

*--results-history-name*=_<resultsHistoryName>_::
  The history name for your test results (an arbitrary string label; default: the application's label from the APK manifest). All tests which use the same history name will have their results grouped together in the Firebase console in a time-ordered test history list.

*--num-flaky-test-attempts*=_<flakyTestAttempts>_::
  The number of times a TestExecution should be re-attempted if one or more of its test cases fail for any reason. The maximum number of reruns allowed is 10. Default is 0, which implies no reruns.

*--shard-time*=_<shardTime>_::
  The max amount of seconds each shard should run.

*--num-test-runs*=_<repeatTests>_::
  The amount of times to run the test executions.

*--max-test-shards*=_<maxTestShards>_::
  The amount of matrices to split the tests across.

*--smart-flank-gcs-path*=_<smartFlankGcsPath>_::
  Google cloud storage path to save test timing data used by smart flank.

*--smart-flank-disable-upload*::
  Disables smart flank JUnit XML uploading. Useful for preventing timing data from being updated.

*--disable-sharding*::
  Disable sharding.

*--test-targets-always-run*=_<testTargetsAlwaysRun>_[,_<testTargetsAlwaysRun>_...]::
  A list of one or more test methods to be added at the top of every shard. Flank doesn't ensure execution order of added tests.

*--files-to-download*=_<filesToDownload>_[,_<filesToDownload>_...]::
  A list of paths that will be downloaded from the resulting bucket to the local results folder after the test is complete. These must be absolute paths (for example, --files-to-download /images/tempDir1,/data/local/tmp/tempDir2). Path names are restricted to the characters a-zA-Z0-9_-./+.

*--project*=_<project>_::
  The Google Cloud Platform project name to use for this invocation. If omitted, then the project from the service account credential is used

*--local-result-dir*=_<localResultsDir>_::
  Saves test result to this local folder. Deleted before each run.

*--run-timeout*=_<runTimeout>_::
  The max time this test run can execute before it is cancelled (default: unlimited).

*--full-junit-result*::
  Enable create additional local junit result on local storage with failure nodes on passed flaky tests.

*--ignore-failed-tests*::
  Terminate with exit code 0 when there are failed tests. Useful for Fladle and other gradle plugins that don't expect the process to have a non-zero exit code. The JUnit XML is used to determine failure. (default: false)

*--keep-file-path*::
  Keeps the full path of downloaded files. Required when file names are not unique.

*--output-style*=_<outputStyle>_::
  Output style of execution status. May be one of [verbose, multi, single]. For runs with only one test execution the default value is 'verbose', in other cases 'multi' is used as the default. The output style 'multi' is not displayed correctly on consoles which don't support ansi codes, to avoid corrupted output use `single` or `verbose`.

*--disable-results-upload*::
  Disables flank results upload on gcloud storage.

*--default-test-time*=_<defaultTestTime>_::
  Set default test time used for calculating shards.

*--use-average-test-time-for-new-tests*::
  Enable using average time from previous tests duration when using SmartShard and tests did not run before.

*--test*=_<test>_::
  The path to the test package (a zip file containing the iOS app and XCTest files). The given path may be in the local filesystem or in Google Cloud Storage using a URL beginning with gs://. Note: any .xctestrun file in this zip file will be ignored if --xctestrun-file is specified.

*--xctestrun-file*=_<xctestrunFile>_::
  The path to an .xctestrun file that will override any .xctestrun file contained in the --test package. Because the .xctestrun file contains environment variables along with test methods to run and/or ignore, this can be useful for customizing or sharding test suites. The given path may be in the local filesystem or in Google Cloud Storage using a URL beginning with gs://.

*--xcode-version*=_<xcodeVersion>_::
  The version of Xcode that should be used to run an XCTest. Defaults to the latest Xcode version supported in Firebase Test Lab. This Xcode version must be supported by all iOS versions selected in the test matrix.

*--test-targets*=_<testTargets>_[,_<testTargets>_...]::
  A list of one or more test method names to run (default: run all test targets).

*--dump-shards*::
  Measures test shards from given test apks and writes them into ios_shards.json file instead of executing.

// end::picocli-generated-man-section-options[]

// end::picocli-generated-full-manpage[]