@startuml

skinparam componentStyle rectangle

note as N #ffffff
* Brighter tasks are required by the darker tasks.
* The brightness means how fast the task will start.
* White tasks are starting first.
end note

[Authorize] #fbfbfb
[OutputDir] #fbfbfb
[ParseApkInfo] #fbfbfb
[ParseTestCases] #fbfbfb
[LoadPreviousDurations] #dfdfdf
[PrepareShards] #c3c3c3
[Dispatch.Shards] #a7a7a7
[DumpShards] #a7a7a7
[ExecuteTests.Results] #a7a7a7
[AvailableDevices] #a7a7a7
[Dispatch.Tests] #8b8b8b
[Dispatch.Failed] #8b8b8b
[InvokeDevices] #8b8b8b
[ExecuteTests] #6f6f6f
[GenerateReport] #535353
[CompleteTests] #373737

[Dispatch.Shards] --> [PrepareShards]
[Dispatch.Tests] --> [ParseApkInfo]
[Dispatch.Tests] --> [Authorize]
[Dispatch.Tests] --> [PrepareShards]
[Dispatch.Tests] --> [AvailableDevices]
[Dispatch.Tests] --> [Dispatch.Shards]
[Dispatch.Tests] --> [ExecuteTests.Results]
[Dispatch.Failed] --> [PrepareShards]
[Dispatch.Failed] --> [Dispatch.Shards]
[Dispatch.Failed] --> [ExecuteTests.Results]
[DumpShards] --> [PrepareShards]
[DumpShards] --> [OutputDir]
[ExecuteTests] --> [InvokeDevices]
[ExecuteTests] --> [Dispatch.Tests]
[ExecuteTests] --> [Dispatch.Failed]
[CompleteTests] --> [GenerateReport]
[CompleteTests] --> [DumpShards]
[GenerateReport] --> [ExecuteTests]
[GenerateReport] --> [OutputDir]
[ExecuteTests.Results] --> [PrepareShards]
[AvailableDevices] --> [PrepareShards]
[InvokeDevices] --> [Authorize]
[InvokeDevices] --> [PrepareShards]
[InvokeDevices] --> [AvailableDevices]
[LoadPreviousDurations] --> [ParseTestCases]
[PrepareShards] --> [ParseTestCases]
[PrepareShards] --> [LoadPreviousDurations]

@enduml
