site_name: Flank
site_url:
site_author:
site_description:
repo_name: Flank
repo_url: https://github.com/Flank/flank
edit_uri: ""
copyright:
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  features:
    - tabs
    - search.highlight
language: en
include_search_page: false
search_index_only: true
nav:
  - Home: index.md
  - Quick Start:
      - Quick Start: QuickStart/index.md
  - Configuration:
      - Configuration: Configuration/index.md
  - Changelog:
      - Changelog: Changelog/index.md
  - Results:
      - Results: Results/index.md
plugins:
  - search