# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  pull_request:
    types: [ closed ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    # if: contains(github.event.pull_request.labels.*.name, 'some-defined-label')
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5
        with:
          release_branches: release.*
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: 20.1.2
