name: flank-scripts-macos-workflow

on:
  push:
    branches: 
      - master
  pull_request:
    branches: [master]
    path: 
      - /flank-scripts/**

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Gradle check
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-executable: "./flank-scripts/gradlew"
        arguments: "-p flank-scripts check"
