name: integration-tests

on:
  pull_request:
    types: [ edited, synchronize ]
  pull_request_review:
    types: submitted

jobs:
  check_approve_count:
    runs-on: ubuntu-latest
    outputs:
      approve_count: ${{ steps.reviews.outputs.approved }}
    steps:
      - name: Count approve count
        id: reviews
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo $PR_NUMBER
          echo $GITHUB_REF
          export count=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/flank/flank/pulls/${PR_NUMBER}/reviews -s | grep -i -c '"state": "APPROVED"')
          echo $count
          echo "::set-output name=approved::${count}"

      - name: Print current approve count
        run: |
          echo "Current Approve count ${{ steps.reviews.outputs.approved }}"

  integration-tests-unix:
    needs: [ check_approve_count ]
    if: 'needs.check_approve_count.outputs.approve_count >= 2'
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: '${{ secrets.GITHUB_TOKEN }}'

      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle clean build
        uses: eskatos/gradle-command-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_REF: ${{ github.ref }}
        with:
          arguments: "clean build"

      - name: Prepare Google Service Account
        env:
          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
        run: |
          GCLOUD_DIR="$HOME/.config/gcloud/"
          mkdir -p "$GCLOUD_DIR"
          echo "$GCLOUD_KEY" | base64 --decode > "$GCLOUD_DIR/application_default_credentials.json"

      - name: Gradle Integration Tests Android
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: "--info :integration_tests:test --tests IntegrationTests.shouldMatchAndroidSuccessExitCodeAndPattern -Dflank-path=../test_runner/build/libs/flank.jar -Dyml-path=./src/test/resources/flank_android.yml"

      - name: Gradle Integration Tests iOS
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: "--info :integration_tests:test --tests IntegrationTests.shouldMatchIosSuccessExitCodeAndPattern -Dflank-path=../test_runner/build/libs/flank.jar -Dyml-path=./src/test/resources/flank_ios.yml"

  integration-tests-windows:
    needs: [ check_approve_count ]
    if: 'needs.check_approve_count.outputs.approve_count >= 2'
    runs-on: windows-2019
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-2-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-2-gradle-

      - name: Gradle clean build
        shell: cmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_REF: ${{ github.ref }}
        run: |
          gradlew.bat clean build

      - name: Prepare Google Service Account
        shell: cmd
        env:
          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
        run: |
          set GCLOUD_DIR="%HOMEPATH%\.config\gcloud"
          mkdir %GCLOUD_DIR%
          echo %GCLOUD_KEY% > gcloud_key.txt
          certutil -decode gcloud_key.txt %GCLOUD_DIR%\application_default_credentials.json

      - name: Gradle Integration Tests Android
        uses: eskatos/gradle-command-action@v1
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          arguments: "--info :integration_tests:test --tests IntegrationTests.shouldMatchAndroidSuccessExitCodeAndPattern -Dflank-path=../test_runner/build/libs/flank.jar -Dyml-path=./src/test/resources/flank_android.yml"

