name: Integration tests Full Suite
on:
  repository_dispatch:
    types: [ integration-test ]
jobs:
  integration-tests-full-suite-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: rocket

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: '${{ secrets.GITHUB_TOKEN }}'

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          submodules: true

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle clean build
        uses: eskatos/gradle-command-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_REF: ${{ github.event.client_payload.pull_request.head.ref }}
        with:
          arguments: "clean build"

      - name: Prepare Google Service Account
        env:
          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
        run: |
          GCLOUD_DIR="$HOME/.config/gcloud/"
          mkdir -p "$GCLOUD_DIR"
          echo "$GCLOUD_KEY" | base64 --decode > "$GCLOUD_DIR/application_default_credentials.json"

      - name: Gradle Integration Tests Android
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: "--info :integration_tests:test"

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: '**/build/test-results/integrationTests/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Publish Integration Test Results
#        uses: EnricoMi/publish-unit-test-result-action@v1.5
#        if: always()
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          files: integration_tests/build/test-results/integrationTests/**/*.xml
