name: Recovering secrets

on:
  push:
  workflow_dispatch:

jobs:
  openssl:
    name: Recover With OpenSSL
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - env:
          BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          FLANK_RELEASE_APP_ID: ${{ secrets.FLANK_RELEASE_APP_ID }}
          FLANK_RELEASE_PRIVATE_KEY: ${{ secrets.FLANK_RELEASE_PRIVATE_KEY }}
          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
          JFROG_USER: ${{ secrets.JFROG_USER }}
          MVN_CENTRAL_PASSWORD: ${{ secrets.MVN_CENTRAL_PASSWORD }}
          MVN_CENTRAL_USER: ${{ secrets.MVN_CENTRAL_USER }}
          PGP_SIGNING_KEY: ${{ secrets.PGP_SIGNING_KEY }}
          ZENHUB_API_KEY: ${{ secrets.ZENHUB_API_KEY }}
          OPENSSL_PASSWORD: ${{ secrets.OPENSSL_PASSWORD }}
          OPENSSL_ITER: ${{ secrets.OPENSSL_ITER }}
        run: |
          echo "BUGSNAG_API_KEY (openssl) = $(echo "${BUGSNAG_API_KEY}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
          echo "CODECOV_TOKEN (openssl) = $(echo "${CODECOV_TOKEN}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
          echo "FLANK_RELEASE_APP_ID (openssl) = $(echo "${FLANK_RELEASE_APP_ID}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
          echo "FLANK_RELEASE_PRIVATE_KEY (openssl) = $(echo "${FLANK_RELEASE_PRIVATE_KEY}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
          echo "GCLOUD_KEY (openssl) = $(echo "${GCLOUD_KEY}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
          echo "GOOGLE_APPLICATION_CREDENTIALS (openssl) = $(echo "${GOOGLE_APPLICATION_CREDENTIALS}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
          echo "GRADLE_ENTERPRISE_ACCESS_KEY (openssl) = $(echo "${GRADLE_ENTERPRISE_ACCESS_KEY}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
          echo "JFROG_API_KEY (openssl) = $(echo "${JFROG_API_KEY}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
          echo "JFROG_USER (openssl) = $(echo "${JFROG_USER}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
          echo "MVN_CENTRAL_PASSWORD (openssl) = $(echo "${MVN_CENTRAL_PASSWORD}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
          echo "MVN_CENTRAL_USER (openssl) = $(echo "${MVN_CENTRAL_USER}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
          echo "PGP_SIGNING_KEY (openssl) = $(echo "${PGP_SIGNING_KEY}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
          echo "ZENHUB_API_KEY (openssl) = $(echo "${ZENHUB_API_KEY}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
