name: "Release Flank Wrapper"

on:
  push:
    paths:
      - 'flank_wrapper/**'
    branches:
      - 'master'

# TODO: update workflow permissions to least privilege after auditing all the APIs used
# permissions:  # limit the permissions of the GITHIUB_TOKEN to reading repository contents
#   contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit
        # TODO: change to 'egress-policy: block' after auditing a number of runs and updating the allowed-endpoints option accordingly

    - uses: actions/checkout@v4
    - uses: gradle/wrapper-validation-action@v3

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Gradle Upload to Github packages and Github release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew flank-wrapper:releaseFlankWrapper -PGITHUB_TOKEN="$GH_TOKEN"
