name: "Release Flank Wrapper"

on:
  push:
    paths:
      - 'flank_wrapper/**'
    branches:
      - 'master'

# TODO: update workflow permissions to least privilege after auditing all the APIs used
# permissions:  # limit the permissions of the GITHIUB_TOKEN to reading repository contents
#   contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit
        # TODO: change to 'egress-policy: block' after auditing a number of runs and updating the allowed-endpoints option accordingly

    - uses: actions/checkout@v4
    - uses: gradle/wrapper-validation-action@v1

    - name: Gradle Upload to Github packages and Github release
      uses: gradle/gradle-build-action@v2.10.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        arguments: "flank_wrapper:releaseFlankWrapper -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
