name: Release Flank Wrapper

on:
  push:
    paths:
      - 'flank_wrapper/**'
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: gradle/wrapper-validation-action@v1

    - name: Gradle Upload to Github packages and Github release
      uses: eskatos/gradle-command-action@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      with:
        arguments: "flank_wrapper:releaseFlankWrapper -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
