name: "Test SendFlank"
on:
  pull_request:
    branches:
      - master
jobs:
  say_hello:
      runs-on: ubuntu-latest
      steps:
      - name: Post Message of Flank Release
        uses: Flank/flank@master
        with:
          xoxctoken: ${{ secrets.SLACK_XOXCTOKEN }}
          message: This is a test message. ignore
          channel: ${{ secrets.SLACK_CHANNEL}}
          cookie: ${{ secrets.SLACK_COOKIE}}