name: Trunk Check
on: pull_request
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  trunk_check_macos:
    name: Trunk Check CI [macOS]
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Linters/Formatters
        uses: actions/cache@v2
        with:
          path: ~/.cache/trunk
          key: trunk-${{ runner.os }}

      - name: Trunk Check
        uses: trunk-io/trunk-action@v0.4.0-beta

  trunk_check_ubuntu:
    name: Trunk Check CI [ubuntu]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Linters/Formatters
        uses: actions/cache@v2
        with:
          path: ~/.cache/trunk
          key: trunk-${{ runner.os }}

      - name: Trunk Check
        uses: trunk-io/trunk-action@v0.4.0-beta
