name: windows-workflow

on:
  pull_request:
    branches:
      - '*'

permissions:  # limit the permissions of the GITHIUB_TOKEN to reading repository contents
  contents: read

jobs:
  build:
    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
      contents: read  # for actions/checkout to fetch code
    runs-on: windows-latest

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v4
    - uses: gradle/wrapper-validation-action@v3
    - uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-2-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-2-gradle-

    - name: Gradle clean build
      uses: gradle/gradle-build-action@v3.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HEAD_REF: ${{ github.head_ref }}
      with:
        arguments: "clean build"
