name: windows-workflow

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - '*'
    paths:
      - '**'
      - '!flank-scripts/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Display the java version
        run: java -version
        shell: bash

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle clean build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: "clean build"
