name:  Flank WSL 

on: 
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true

    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-2-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-2-gradle-

    - uses: Vampire/setup-wsl@v1
      with:
        distribution: Ubuntu-18.04

    - name: Build Flank
      run: |
        ls
        ./gradlew clean build


    - name: Prepare Google Service Account
      run: |
          GCLOUD_DIR="$HOME/.config/gcloud/"
          mkdir -p "$GCLOUD_DIR"
          echo "$GCLOUD_KEY" | base64 --decode > "$GCLOUD_DIR/application_default_credentials.json"

    - name: Integration Tests Android
      run: |
          gradlew --info :integration_tests:test --tests IntegrationTests.shouldMatchAndroidSuccessExitCodeAndPattern -Dflank-path=../test_runner/build/libs/flank.jar -Dyml-path=./src/test/resources/flank_android.yml
    
    - name: Integration Tests iOS
      run: |
          gradlew --info :integration_tests:test --tests IntegrationTests.shouldMatchIosSuccessExitCodeAndPattern -Dflank-path=../test_runner/build/libs/flank.jar -Dyml-path=./src/test/resources/flank_ios.yml
